# Copyright 2026 OASIS Open
# SPDX-License-Identifier: Apache-2.0
# Authored by Michael Coletta, Technical Advisor to OASIS Open.
"""converters/docbook-to-markdown: DocBook to OASIS Markdown, per profile.

The end-to-end test converts the DMLex v1.0 OS DocBook source
(oasis-tcs/lexidma at e3c0626, dmlex-v1.0/specification) with the dmlex
profile and requires the Markdown edition committed in MColetta-OASIS/lexidma
(branch markdown-conversion, 29a2b29), byte for byte, and every figure with
it. It needs the network, xmllint, Graphviz and m4; CI sets
REQUIRE_CONVERTER=1 so a missing tool fails rather than skips.

The unit tests feed the converter small DocBook documents to pin what the
profile switches and what the converter refuses.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys

import pytest

from conftest import FIXTURES, REPO_ROOT

CONV = REPO_ROOT / "converters" / "docbook-to-markdown"
BUILD = CONV / "build.sh"
DOCBOOK2MD = CONV / "docbook2md.py"
EDITION = FIXTURES / "verify_md" / "dmlex-v1.0-os"
TCS = "https://github.com/oasis-tcs/lexidma.git"
TCS_SHA = "e3c0626fddc29251aaf74f3357fd6d6167b89b1d"
REQUIRED = bool(os.environ.get("REQUIRE_CONVERTER"))


def _need(*tools):
    missing = [t for t in tools if shutil.which(t) is None]
    if missing:
        if REQUIRED:
            pytest.fail(f"missing {missing} with REQUIRE_CONVERTER=1")
        pytest.skip(f"missing {missing} (CI sets REQUIRE_CONVERTER=1)")


@pytest.fixture(scope="module")
def dmlex_source(tmp_path_factory):
    _need("git", "xmllint", "dot", "m4")
    root = tmp_path_factory.mktemp("tcs") / "lexidma"
    try:
        for cmd in (["git", "clone", "-q", "--filter=blob:none", "--no-checkout", TCS, str(root)],
                    ["git", "-C", str(root), "sparse-checkout", "set", "dmlex-v1.0/specification"],
                    ["git", "-C", str(root), "checkout", "-q", TCS_SHA]):
            subprocess.run(cmd, check=True, capture_output=True, timeout=600)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        if REQUIRED:
            raise
        pytest.skip(f"cannot fetch oasis-tcs/lexidma: {e}")
    return root / "dmlex-v1.0" / "specification"


def titles(svg):
    return sorted(re.findall(r"<title>([^<]*)</title>", svg.read_text(encoding="utf-8")))


def test_dmlex_converts_to_the_committed_edition_byte_for_byte(dmlex_source, tmp_path):
    before = subprocess.run(["git", "-C", str(dmlex_source), "status", "--porcelain", "--ignored"],
                            capture_output=True, text=True, check=True).stdout
    out = tmp_path / "out"
    r = subprocess.run(["bash", str(BUILD), "--profile", "dmlex", str(dmlex_source), str(out)],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stdout + r.stderr
    assert "copied 49 images" in r.stdout
    made = out / "dmlex-v1.0-os.md"
    assert made.read_bytes() == (EDITION / "dmlex-v1.0-os.md").read_bytes()
    edition_files = sorted(p.relative_to(EDITION) for p in EDITION.rglob("*")
                           if p.is_file() and not p.name.startswith("published-"))
    assert sorted(p.relative_to(out) for p in out.rglob("*") if p.is_file()) == edition_files
    for rel in edition_files:
        if rel.name == "dmlex_uml.svg":
            # Generated by the TC's nvh2dot.py, whose cluster order follows a
            # Python set: the same nodes and edges, laid out per run.
            assert titles(out / rel) == titles(EDITION / rel)
        else:
            assert (out / rel).read_bytes() == (EDITION / rel).read_bytes(), rel
    after = subprocess.run(["git", "-C", str(dmlex_source), "status", "--porcelain", "--ignored"],
                           capture_output=True, text=True, check=True).stdout
    assert after == before, "the build wrote into the source tree"


def test_the_build_verifies_against_the_published_page(dmlex_source, tmp_path):
    _need("pandoc")
    out = tmp_path / "out"
    r = subprocess.run(["bash", str(BUILD), "--profile", "dmlex", str(dmlex_source), str(out),
                        str(EDITION / "published-dmlex-v1.0-os.html")], capture_output=True, text=True)
    assert r.returncode == 0 and r.stdout.rstrip().endswith("RESULT: PASS"), r.stdout[-3000:] + r.stderr
    report = json.loads((out / "dmlex-v1.0-os-verification.json").read_text(encoding="utf-8"))
    assert report["diff_regions"] == 0 and report["code_blocks_markdown"] == 316


def test_the_build_needs_a_profile(tmp_path):
    r = subprocess.run(["bash", str(BUILD), str(tmp_path), str(tmp_path / "o")], capture_output=True, text=True)
    assert r.returncode == 2 and "--profile" in r.stderr


DOC = """<?xml version="1.0"?>
<article status="Committee Specification Draft 01">
 <articleinfo><title>Widget Spec Version 1.0</title><pubdate>1 May 2026</pubdate>
  <releaseinfo role="OASIS-specification-this">https://docs.oasis-open.org/w/v1.0/csd01/w-v1.0-csd01.html</releaseinfo>
  <authorgroup><editor><firstname>Ada</firstname><surname>Lovelace</surname><email>ada@example.org</email></editor></authorgroup>
 </articleinfo>
 <section id="intro"><title>Introduction</title>
  <para>Implementations <glossterm>must</glossterm> do this.</para>
  <para condition="html">Shown only in a non-OASIS build.</para>
  <para condition="oasis">Shown in the OASIS build.</para>
  <graphic fileref="fig.svg" contentwidth="10cm"/>
  <programlisting xml:base="examples/a.nvh">entry: x</programlisting>
  BLOCK
 </section>
</article>
"""


def convert(tmp_path, profile=None, block=""):
    src = tmp_path / "doc.xml"
    src.write_text(DOC.replace("BLOCK", block), encoding="utf-8")
    args = [sys.executable, str(DOCBOOK2MD), str(src), str(tmp_path / "doc.md")]
    if profile is not None:
        (tmp_path / "profile.json").write_text(json.dumps(profile), encoding="utf-8")
        args += ["--profile", str(tmp_path / "profile.json")]
    r = subprocess.run(args, capture_output=True, text=True)
    md = (tmp_path / "doc.md").read_text(encoding="utf-8") if (tmp_path / "doc.md").exists() else ""
    return r, md


def test_the_core_defaults_leave_key_words_as_written(tmp_path):
    r, md = convert(tmp_path)
    assert r.returncode == 0, r.stderr
    assert "Implementations must do this." in md
    assert '<img src="fig.svg" alt="" width="354">' in md  # 10cm at 90 dpi
    assert "```\nentry: x\n```" in md  # .nvh has no default fence language


def test_the_profile_switches_key_words_figure_width_and_fence_language(tmp_path):
    r, md = convert(tmp_path, {"glossterm_upper": True, "figure_dpi": 96,
                               "code_languages": {".nvh": "nvh"}})
    assert r.returncode == 0, r.stderr
    assert "Implementations MUST do this." in md
    assert 'width="378"' in md  # 10cm at 96 dpi
    assert "```nvh\nentry: x\n```" in md


def test_the_dmlex_profile_is_what_the_dmlex_edition_needs():
    profile = json.loads((CONV / "profiles" / "dmlex" / "profile.json").read_text(encoding="utf-8"))
    assert profile["glossterm_upper"] is True and profile["figure_dpi"] == 90
    assert profile["code_languages"][".nvh"] == "nvh"


def test_a_non_oasis_condition_is_dropped_as_the_stylesheet_drops_it(tmp_path):
    r, md = convert(tmp_path)
    assert "Shown in the OASIS build." in md
    assert "non-OASIS" not in md


def test_an_element_the_converter_does_not_know_stops_it(tmp_path):
    """A table flattened into paragraphs keeps its words and loses its meaning."""
    table = ("<informaltable><tgroup cols='2'><tbody><row><entry>a</entry><entry>b</entry></row>"
             "</tbody></tgroup></informaltable>")
    r, _ = convert(tmp_path, block=table)
    assert r.returncode == 1
    assert "UNHANDLED block <informaltable>" in r.stderr


def _article(tmp_path, body, profile=None):
    doc = DOC.split(" <section id=\"intro\">")[0] + body + "\n</article>\n"
    src = tmp_path / "a.xml"
    src.write_text(doc, encoding="utf-8")
    args = [sys.executable, str(DOCBOOK2MD), str(src), str(tmp_path / "a.md")]
    r = subprocess.run(args, capture_output=True, text=True)
    md = (tmp_path / "a.md").read_text(encoding="utf-8") if (tmp_path / "a.md").exists() else ""
    return r, md


def test_content_outside_a_section_stops_the_conversion(tmp_path):
    r, _ = _article(tmp_path, "<para>Orphan text.</para><section id='s'><title>S</title><para>x</para></section>")
    assert r.returncode == 1 and "UNHANDLED" in r.stderr and "para" in r.stderr


def test_a_hidden_section_keeps_its_number_as_the_stylesheet_does(tmp_path):
    """The stylesheet hides a non-OASIS section but still numbers it."""
    r, md = _article(tmp_path, "<section id='one' condition='html'><title>One</title><para>h</para></section>"
                                "<section id='two'><title>Two</title><para>See <xref linkend='three'/>.</para></section>"
                                "<section id='three'><title>Three</title><para>t</para></section>")
    assert r.returncode == 0, r.stderr
    assert "# 2 Two" in md and "# 3 Three" in md and "Section 3" in md and "One" not in md


def test_lettered_or_continued_lists_stop_the_conversion(tmp_path):
    for attrs in ("numeration='loweralpha'", "continuation='continues'"):
        r, _ = _article(tmp_path, f"<section id='s'><title>S</title><orderedlist {attrs}>"
                                  "<listitem><para>a</para></listitem></orderedlist></section>")
        assert r.returncode == 1 and "UNHANDLED" in r.stderr, attrs


def test_characters_markdown_would_read_as_markup_are_escaped(tmp_path):
    r, md = _article(tmp_path, "<section id='s'><title>S</title><para>Cost $5 and $6, 2^10^ items.</para>"
                                "<para>2024. was a year.</para><para># not a heading</para>"
                                "<para>Write &amp;copy; literally.</para></section>")
    assert r.returncode == 0, r.stderr
    assert "\\$5 and \\$6" in md and "2\\^10\\^" in md
    assert "2024\\. was a year." in md and "\\# not a heading" in md and "&amp;copy;" in md


def test_superscript_and_subscript_keep_their_meaning(tmp_path):
    r, md = _article(tmp_path, "<section id='s'><title>S</title><para>2<superscript>10</superscript> "
                                "H<subscript>2</subscript>O</para></section>")
    assert r.returncode == 0 and "2<sup>10</sup>" in md and "H<sub>2</sub>O" in md


def test_an_xref_takes_its_xreflabel_or_endterm_and_never_comes_out_empty(tmp_path):
    r, md = _article(tmp_path, "<section id='s'><title>S</title>"
                                "<para id='p1' xreflabel='the rule'>Rule.</para><para id='p2'>Other.</para>"
                                "<para><phrase id='t'>the term</phrase></para>"
                                "<para>See <xref linkend='p1'/> and <xref linkend='s' endterm='t'/>.</para></section>")
    assert r.returncode == 0, r.stderr
    assert "[the rule](#p1)" in md and "[the term](#s)" in md
    r, _ = _article(tmp_path, "<section id='s'><title>S</title><para id='p2'>x</para>"
                              "<para>See <xref linkend='p2'/>.</para></section>")
    assert r.returncode == 1 and "no text" in r.stderr


def test_a_source_path_with_a_space_builds(tmp_path, dmlex_source):
    spaced = tmp_path / "spec dir"
    shutil.copytree(dmlex_source, spaced, ignore=shutil.ignore_patterns(".git"))
    r = subprocess.run(["bash", str(BUILD), "--profile", "dmlex", str(spaced), str(tmp_path / "o")],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stdout[-2000:] + r.stderr[-2000:]
    assert (tmp_path / "o" / "dmlex-v1.0-os.md").read_bytes() == (EDITION / "dmlex-v1.0-os.md").read_bytes()


def test_a_failing_prebuild_and_a_missing_entity_say_so(tmp_path, dmlex_source):
    prof = tmp_path / "prof"
    shutil.copytree(CONV / "profiles" / "dmlex", prof)
    (prof / "prebuild.sh").write_text("#!/bin/sh\nexit 3\n")
    r = subprocess.run(["bash", str(BUILD), "--profile", str(prof), str(dmlex_source), str(tmp_path / "o")],
                       capture_output=True, text=True)
    assert r.returncode != 0 and "prebuild" in r.stderr
    p = json.loads((prof / "profile.json").read_text())
    p["basename"] = "x-{nosuchentity}"
    p["prebuild"] = ""
    (prof / "profile.json").write_text(json.dumps(p))
    r = subprocess.run(["bash", str(BUILD), "--profile", str(prof), str(dmlex_source), str(tmp_path / "o")],
                       capture_output=True, text=True)
    assert r.returncode == 2 and "nosuchentity" in r.stderr and "Traceback" not in r.stderr
